/**
 * 主题定义
 * 每个主题包含默认变量和样式生成函数
 * 所有样式均为 inline style，确保微信公众号兼容性
 */
const THEMES = {
  default: {
    name: '默认简洁',
    vars: {
      accentColor: '#07c160',
      fontFamily: '-apple-system, BlinkMacSystemFont, "Helvetica Neue", Arial, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
      fontSize: 15,
      lineHeight: 1.75,
      textColor: '#333333',
      mutedColor: '#666666',
    },
    styles(vars) {
      return {
        wrapper: `font-family: ${vars.fontFamily}; font-size: ${vars.fontSize}px; color: ${vars.textColor}; line-height: ${vars.lineHeight}; word-wrap: break-word; -webkit-text-size-adjust: 100%;`,
        h1: `display: block; font-size: 22px; font-weight: bold; color: #1a1a1a; margin: 28px 0 14px 0; line-height: 1.4; text-align: center; letter-spacing: 1px;`,
        h2: `display: block; font-size: 18px; font-weight: bold; color: #1a1a1a; margin: 24px 0 12px 0; line-height: 1.4; border-bottom: 2px solid ${vars.accentColor}; padding-bottom: 6px;`,
        h3: `display: block; font-size: ${vars.fontSize + 2}px; font-weight: bold; color: #1a1a1a; margin: 20px 0 10px 0; line-height: 1.4; padding-left: 10px; border-left: 3px solid ${vars.accentColor};`,
        h4: `display: block; font-size: ${vars.fontSize + 1}px; font-weight: bold; color: #1a1a1a; margin: 16px 0 8px 0; line-height: 1.4;`,
        h5: `display: block; font-size: ${vars.fontSize}px; font-weight: bold; color: #555555; margin: 14px 0 7px 0; line-height: 1.4;`,
        h6: `display: block; font-size: ${vars.fontSize - 1}px; font-weight: bold; color: #777777; margin: 12px 0 6px 0; line-height: 1.4;`,
        p: `display: block; margin: 12px 0; line-height: ${vars.lineHeight}; color: ${vars.textColor}; font-size: ${vars.fontSize}px;`,
        strong: `font-weight: bold; color: #1a1a1a;`,
        em: `font-style: italic;`,
        del: `text-decoration: line-through; color: #999999;`,
        inlineCode: `background-color: #f5f5f5; padding: 2px 5px; border-radius: 3px; font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace; font-size: 87%; color: #e83e8c;`,
        pre: `display: block; background-color: #f8f8f8; border-radius: 6px; padding: 16px; margin: 16px 0; overflow-x: auto;`,
        preCode: `background-color: transparent; padding: 0; font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace; font-size: 13px; line-height: 1.6; color: #333333; white-space: pre;`,
        blockquote: `display: block; border-left: 4px solid ${vars.accentColor}; padding: 10px 16px; margin: 16px 0; background-color: #f9f9f9; color: ${vars.mutedColor};`,
        ul: `display: block; padding-left: 24px; margin: 12px 0;`,
        ol: `display: block; padding-left: 24px; margin: 12px 0;`,
        li: `display: list-item; margin: 6px 0; line-height: ${vars.lineHeight}; font-size: ${vars.fontSize}px; color: ${vars.textColor};`,
        a: `color: ${vars.accentColor}; text-decoration: none;`,
        img: `display: block; max-width: 100%; height: auto; margin: 16px auto;`,
        hr: `display: block; border: none; border-top: 1px solid #e5e7eb; margin: 28px 0;`,
        table: `border-collapse: collapse; width: 100%; margin: 16px 0; font-size: ${vars.fontSize - 1}px;`,
        th: `background-color: #f5f5f5; border: 1px solid #e5e7eb; padding: 8px 12px; text-align: left; font-weight: bold; color: #1a1a1a;`,
        td: `border: 1px solid #e5e7eb; padding: 8px 12px; color: ${vars.textColor};`,
      };
    },
  },

  tech: {
    name: '科技感',
    vars: {
      accentColor: '#4f9cf9',
      fontFamily: '"PingFang SC", "Microsoft YaHei", -apple-system, BlinkMacSystemFont, Arial, sans-serif',
      fontSize: 15,
      lineHeight: 1.8,
      textColor: '#2d3748',
      mutedColor: '#718096',
    },
    styles(vars) {
      return {
        wrapper: `font-family: ${vars.fontFamily}; font-size: ${vars.fontSize}px; color: ${vars.textColor}; line-height: ${vars.lineHeight}; word-wrap: break-word;`,
        h1: `display: block; font-size: 24px; font-weight: 700; color: ${vars.accentColor}; margin: 28px 0 14px 0; line-height: 1.3; text-align: center; letter-spacing: 2px;`,
        h2: `display: block; font-size: 19px; font-weight: 700; color: #1a202c; margin: 24px 0 12px 0; line-height: 1.4; background-color: #ebf4ff; padding: 8px 14px; border-left: 4px solid ${vars.accentColor};`,
        h3: `display: block; font-size: ${vars.fontSize + 2}px; font-weight: 600; color: ${vars.accentColor}; margin: 20px 0 10px 0; line-height: 1.4;`,
        h4: `display: block; font-size: ${vars.fontSize + 1}px; font-weight: 600; color: #2d3748; margin: 16px 0 8px 0; line-height: 1.4;`,
        h5: `display: block; font-size: ${vars.fontSize}px; font-weight: 600; color: #4a5568; margin: 14px 0 7px 0; line-height: 1.4;`,
        h6: `display: block; font-size: ${vars.fontSize - 1}px; font-weight: 600; color: #718096; margin: 12px 0 6px 0; line-height: 1.4;`,
        p: `display: block; margin: 12px 0; line-height: ${vars.lineHeight}; color: ${vars.textColor}; font-size: ${vars.fontSize}px;`,
        strong: `font-weight: bold; color: #1a202c;`,
        em: `font-style: italic; color: #4a5568;`,
        del: `text-decoration: line-through; color: #a0aec0;`,
        inlineCode: `background-color: #1a202c; padding: 2px 6px; border-radius: 3px; font-family: "SFMono-Regular", Consolas, monospace; font-size: 87%; color: #68d391;`,
        pre: `display: block; background-color: #1a202c; border-radius: 8px; padding: 18px; margin: 16px 0; overflow-x: auto;`,
        preCode: `background-color: transparent; padding: 0; font-family: "SFMono-Regular", Consolas, monospace; font-size: 13px; line-height: 1.6; color: #e2e8f0; white-space: pre;`,
        blockquote: `display: block; border-left: 4px solid ${vars.accentColor}; padding: 12px 16px; margin: 16px 0; background-color: #ebf4ff; color: #2b6cb0; border-radius: 0 6px 6px 0;`,
        ul: `display: block; padding-left: 24px; margin: 12px 0;`,
        ol: `display: block; padding-left: 24px; margin: 12px 0;`,
        li: `display: list-item; margin: 6px 0; line-height: ${vars.lineHeight}; font-size: ${vars.fontSize}px; color: ${vars.textColor};`,
        a: `color: ${vars.accentColor}; text-decoration: none;`,
        img: `display: block; max-width: 100%; height: auto; margin: 16px auto; border-radius: 6px;`,
        hr: `display: block; border: none; border-top: 1px solid #e2e8f0; margin: 28px 0;`,
        table: `border-collapse: collapse; width: 100%; margin: 16px 0; font-size: ${vars.fontSize - 1}px;`,
        th: `background-color: ${vars.accentColor}; border: 1px solid #bee3f8; padding: 10px 14px; text-align: left; font-weight: bold; color: #ffffff;`,
        td: `border: 1px solid #e2e8f0; padding: 8px 14px; color: ${vars.textColor};`,
      };
    },
  },

  literary: {
    name: '文艺清新',
    vars: {
      accentColor: '#8b1a1a',
      fontFamily: 'Georgia, "Times New Roman", "Songti SC", "SimSun", serif',
      fontSize: 16,
      lineHeight: 2.0,
      textColor: '#2d1010',
      mutedColor: '#7a4040',
    },
    styles(vars) {
      return {
        wrapper: `font-family: ${vars.fontFamily}; font-size: ${vars.fontSize}px; color: ${vars.textColor}; line-height: ${vars.lineHeight}; word-wrap: break-word;`,
        h1: `display: block; font-size: 26px; font-weight: bold; color: #1a0808; margin: 32px 0 16px 0; line-height: 1.4; text-align: center; letter-spacing: 3px;`,
        h2: `display: block; font-size: 20px; font-weight: bold; color: #1a0808; margin: 28px 0 14px 0; line-height: 1.4; border-left: 4px solid ${vars.accentColor}; padding-left: 12px;`,
        h3: `display: block; font-size: ${vars.fontSize + 2}px; font-weight: bold; color: ${vars.accentColor}; margin: 22px 0 11px 0; line-height: 1.4;`,
        h4: `display: block; font-size: ${vars.fontSize + 1}px; font-weight: bold; color: #2d1010; margin: 18px 0 9px 0; line-height: 1.4;`,
        h5: `display: block; font-size: ${vars.fontSize}px; font-weight: bold; color: #5a2020; margin: 14px 0 7px 0; line-height: 1.4;`,
        h6: `display: block; font-size: ${vars.fontSize - 1}px; font-weight: bold; color: #7a4040; margin: 12px 0 6px 0; line-height: 1.4;`,
        p: `display: block; margin: 14px 0; line-height: ${vars.lineHeight}; color: ${vars.textColor}; font-size: ${vars.fontSize}px; text-indent: 2em;`,
        strong: `font-weight: bold; color: #1a0808;`,
        em: `font-style: italic; color: ${vars.accentColor};`,
        del: `text-decoration: line-through; color: #b07070;`,
        inlineCode: `background-color: #fdf2f2; padding: 2px 5px; border-radius: 3px; font-family: "SFMono-Regular", Consolas, monospace; font-size: 87%; color: ${vars.accentColor};`,
        pre: `display: block; background-color: #fdf2f2; border-radius: 6px; padding: 16px; margin: 16px 0; border-left: 4px solid ${vars.accentColor}; overflow-x: auto;`,
        preCode: `background-color: transparent; padding: 0; font-family: "SFMono-Regular", Consolas, monospace; font-size: 13px; line-height: 1.6; color: #5a2020; white-space: pre;`,
        blockquote: `display: block; border-left: 4px solid ${vars.accentColor}; padding: 12px 20px; margin: 20px 0; background-color: #fdf2f2; color: ${vars.mutedColor}; font-style: italic;`,
        ul: `display: block; padding-left: 24px; margin: 14px 0;`,
        ol: `display: block; padding-left: 24px; margin: 14px 0;`,
        li: `display: list-item; margin: 8px 0; line-height: ${vars.lineHeight}; font-size: ${vars.fontSize}px; color: ${vars.textColor};`,
        a: `color: ${vars.accentColor}; text-decoration: underline; text-underline-offset: 3px;`,
        img: `display: block; max-width: 100%; height: auto; margin: 20px auto; border-radius: 4px;`,
        hr: `display: block; border: none; border-top: 1px dashed #c8a0a0; margin: 32px 0;`,
        table: `border-collapse: collapse; width: 100%; margin: 16px 0; font-size: ${vars.fontSize - 1}px;`,
        th: `background-color: #fdf2f2; border: 1px solid #e0c0c0; padding: 8px 12px; text-align: left; font-weight: bold; color: #2d1010;`,
        td: `border: 1px solid #e0c0c0; padding: 8px 12px; color: ${vars.textColor};`,
      };
    },
  },

  magazine: {
    name: '现代杂志',
    vars: {
      accentColor: '#c0392b',
      fontFamily: "'Noto Sans SC', 'PingFang SC', 'Microsoft YaHei', sans-serif",
      fontSize: 15,
      lineHeight: 1.85,
      textColor: '#4a4a4a',
      mutedColor: '#888888',
    },
    styles(vars) {
      return {
        wrapper: `font-family: ${vars.fontFamily}; font-size: ${vars.fontSize}px; color: ${vars.textColor}; line-height: ${vars.lineHeight}; word-wrap: break-word; -webkit-text-size-adjust: 100%;`,
        h1: `display: block; font-family: 'Noto Serif SC', 'Songti SC', Georgia, serif; font-size: 24px; font-weight: 700; color: #1a1a1a; margin: 44px 0 8px 0; line-height: 1.4; padding-bottom: 10px;`,
        h1Decoration: `<span style="display:block;width:100%;height:2px;background:linear-gradient(to right, ${vars.accentColor} 40px, #1a1a1a 40px);margin-top:0;margin-bottom:8px;"></span>`,
        h2: `display: block; font-family: 'Noto Serif SC', 'Songti SC', Georgia, serif; font-size: 19px; font-weight: 600; color: #1a1a1a; margin: 36px 0 12px 0; line-height: 1.45; border-left: 5px solid ${vars.accentColor}; padding-left: 12px;`,
        h3: `display: block; font-size: 15px; font-weight: 600; color: #1a1a1a; margin: 28px 0 10px 0; line-height: 1.4; letter-spacing: 0.03em;`,
        h4: `display: block; font-size: ${vars.fontSize}px; font-weight: 600; color: #1a1a1a; margin: 20px 0 8px 0; line-height: 1.4;`,
        h5: `display: block; font-size: ${vars.fontSize - 1}px; font-weight: 600; color: #4a4a4a; margin: 16px 0 6px 0; line-height: 1.4;`,
        h6: `display: block; font-size: ${vars.fontSize - 1}px; font-weight: 600; color: #888888; margin: 14px 0 6px 0; line-height: 1.4;`,
        p: `display: block; font-size: 15.5px; line-height: 1.85; color: ${vars.textColor}; margin-bottom: 20px;`,
        strong: `font-weight: 700; color: #1a1a1a;`,
        em: `font-style: italic; color: ${vars.accentColor};`,
        del: `text-decoration: line-through; color: #aaaaaa;`,
        inlineCode: `font-family: 'JetBrains Mono', 'Fira Code', Consolas, monospace; font-size: 13px; background-color: #f4f3f0; color: ${vars.accentColor}; padding: 1px 6px; border-radius: 3px; border: 1px solid #d8d5d0;`,
        codeHeader: `display: block; background-color: #2d2d2d; padding: 10px 16px; border-radius: 8px 8px 0 0;`,
        pre: `display: block; background-color: #1e1e1e; border-radius: 0 0 8px 8px; padding: 20px; margin: 0; overflow-x: auto;`,
        preCode: `background-color: transparent; padding: 0; font-family: 'JetBrains Mono', 'Fira Code', Consolas, monospace; font-size: 13.5px; line-height: 1.7; color: #d4d4d4; white-space: pre;`,
        blockquote: `display: block; border-left: 3px solid ${vars.accentColor}; padding: 18px 22px; margin: 28px 0; background-color: #f6f4f1; color: #555555; font-style: italic; border-radius: 0 4px 4px 0;`,
        ul: `display: block; padding-left: 22px; margin: 20px 0;`,
        ol: `display: block; padding-left: 24px; margin: 20px 0;`,
        li: `display: list-item; margin: 6px 0; line-height: 1.8; font-size: ${vars.fontSize}px; color: ${vars.textColor};`,
        a: `color: ${vars.accentColor}; text-decoration: underline; text-underline-offset: 3px;`,
        img: `display: block; max-width: 100%; height: auto; margin: 20px auto; border-radius: 6px;`,
        hr: `display: block; border: none; border-top: 1px solid #e0ddd8; margin: 36px 0;`,
        table: `border-collapse: collapse; width: 100%; margin: 28px 0; font-size: 14px;`,
        th: `background-color: #1a1a1a; padding: 12px 16px; text-align: left; font-size: 12px; font-weight: 600; color: #ffffff; letter-spacing: 0.05em;`,
        td: `padding: 11px 16px; color: ${vars.textColor}; border-top: 1px solid #e0ddd8; line-height: 1.5;`,
      };
    },
  },
};
